# Generated by Django 3.1.7 on 2021-04-26 18:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0010_auto_20210425_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_Likes',
            field=models.ManyToManyField(blank=True, related_name='comment_Likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
