# Generated by Django 3.1.7 on 2021-04-27 01:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0013_auto_20210427_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='shares',
            field=models.ManyToManyField(blank=True, null=True, related_name='shares', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='PostShares',
        ),
    ]
