# Generated by Django 3.1.7 on 2021-04-28 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20210428_2348'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPosts',
        ),
    ]
