# Generated by Django 3.2 on 2021-05-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_auto_20210429_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedpost',
            name='quote',
            field=models.TextField(blank=True, null=True),
        ),
    ]
