# Generated by Django 3.2 on 2021-05-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='bookmarks', to='posts.Post'),
        ),
    ]
