# Generated by Django 3.1.7 on 2021-04-17 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_account_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
    ]
