# Generated by Django 3.1.7 on 2021-04-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_account_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='active_status',
            field=models.BooleanField(default=True),
        ),
    ]
