# Generated by Django 3.1.7 on 2021-04-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20210423_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=100, null=True),
        ),
    ]
