# Generated by Django 3.1.7 on 2021-04-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='thread_type',
            field=models.CharField(choices=[('personal', 'Personal'), ('group', 'Group')], default='personal', max_length=15),
        ),
    ]
